const ActionTypes={
    GET_COLOD:"GET_COLOD",
    GET_FIRST_USED_CARD:"GET_FIRST_USED_CARD",
    TAKE_CARD_COMPUTER:"TAKE_CARD_COMPUTER",
    THROW_CARD_COMPUTER:"THROW_CARD_COMPUTER",
    TAKE_CARD_USER:"TAKE_CARD_USER",
    THROW_CARD_USER:"THROW_CARD_USER",
    THROW_SEVEN:"THROW_SEVENS"
}
export default ActionTypes;
