const ActionTypes={
    GET_COLOD:"GET_COLOD",
    GET_COLOD_AGAIN:"GET_COLOD_AGAIN",
    GET_FIRST_USED_CARD:"GET_FIRST_USED_CARD",
    TAKE_CARD_COMPUTER:"TAKE_CARD_COMPUTER",
    THROW_CARD_COMPUTER:"THROW_CARD_COMPUTER",
    TAKE_CARD_USER:"TAKE_CARD_USER",
    THROW_CARD_USER:"THROW_CARD_USER",
    THROW_SEVEN:"THROW_SEVENS",
    CHANGE_MAST:"CHANGE_MAST",
    CHENGE_CORSE:"CENGE_CORSE"
}
export default ActionTypes;
